config/routes.rb
Merchant::Application.routes.draw do
  resources :addresses

  root to: "products#index"
  resources :orders do
    member do
      get :confirm
    end
  end
  resources :order_items

  resources :products

  match '/auth/:provider/callback', to: 'sessions#create', via: :get
  match "/login" => redirect("/auth/twitter"), as: :login, via: :get
  match "/logout" => "sessions#destroy", as: :logout, via: :get

  

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_items, dependent: :destroy
	belongs_to :user
	belongs_to :address
	def total(subtotal)
		@total ||= 0
		@total += subtotal
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :confirm]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params.merge(status: 'submitted'))
        format.html { redirect_to confirm_order_path(@order) }
        format.json { head :no_content }
        session[:order_id] = nil
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to products_path }
      format.json { head :no_content }
    end
  end

  def confirm
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :status, :address_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, :user_id => current_user.id %><br>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/orders/confirm.html.erb
<h2>Thank you for your order!</h2>

<%= link_to "Go back to products.", products_path %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
	<tr>
		<th>Customer</th>
		<td><%= @order.user.name if @order.user %></td>
	</tr>
	<tr>
		<th>Status:</th>
		<td><%= @order.status %></td>
	</tr>
	<tr>
		<th>Items:</th>
		<td><%= @order.order_items.count %></td>
	</tr>
	<%= form_for @order do |f| %>
	<tr>
		<th>Shipping To:</th>
		<td>
			<%= f.select :address_id, current_user.addresses.collect{|a| [a.to_s, a.id]} %><br/>
			<%= link_to "New Address", new_address_path %>
		</td>
	</tr>
	<% end %>
	<tr>
		<th>Items</th>
		<th>Title</th>
		<th>Quantity</th>
		<th>Stock</th>
		<th>Unit Price</th>
		<th>Subtotal</th>
		<th>Order Total</th>
		<th><%= link_to "Empty Cart", @order, data: { confirm: 'Are you sure?' }, method: :delete %></th>
	</tr>
	<% @order.order_items.each do |item| %>
	<tr>
		<% skip if item.nil? %>
		<td><%= image_tag "products/#{item.product.image_url}" %></td>
		<td><%= item.product.title %></td>
		<td><%= link_to item.quantity, edit_order_item_path(item) %></td>
		<td><%= print_stock(item.product.stock, item.quantity) %></td>
		<td><%= print_price(item.product.price) %></td>
		<td><%= print_price(item.subtotal(item)) %></td>
		<td><%= print_price(@order.total(item.subtotal(item))) %></td>
		<td><%= link_to 'Cancel Order', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</table>
<%= render 'form' %>